from odoo import models, fields, api
from datetime import timedelta


class ChatbotSession(models.Model):
    """
    Represents a single chat session between a website visitor and the AI chatbot.

    A session is created the first time a visitor sends a message from the website
    snippet. It stores the visitor's identity (if logged in, the partner is linked;
    otherwise only the browser-generated token is kept), the current LLM-ready
    conversation summary, and a count that mirrors the summarisation logic already
    used in the odoo_mcp_addon history system.
    """

    _name = 'mcp.chatbot.session'
    _description = 'MCP Chatbot Session'
    _order = 'create_date desc'

    # ------------------------------------------------------------------ #
    # Identity                                                             #
    # ------------------------------------------------------------------ #

    name = fields.Char(
        string='Session Name',
        compute='_compute_name',
        store=True,
    )

    # Opaque token generated by the browser widget (UUID-v4).
    # Used to resume a session across page reloads without requiring login.
    session_token = fields.Char(
        string='Session Token',
        required=True,
        index=True,
        copy=False,
    )

    # Populated only when the visitor is a logged-in Odoo portal / internal user.
    partner_id = fields.Many2one(
        'res.partner',
        string='Visitor (Partner)',
        ondelete='set null',
        index=True,
    )

    # ------------------------------------------------------------------ #
    # State                                                                #
    # ------------------------------------------------------------------ #

    state = fields.Selection(
        selection=[
            ('open',   'Open'),
            ('closed', 'Closed'),
        ],
        string='State',
        default='open',
        required=True,
        index=True,
    )

    # Tracks the last time a message was sent in this session.
    # Used by the cron job to close idle sessions after IDLE_TIMEOUT_MINUTES.
    last_activity = fields.Datetime(
        string='Last Activity',
        default=fields.Datetime.now,
        readonly=True,
    )

    # ------------------------------------------------------------------ #
    # History compression (mirrors history.summary logic in odoo_mcp_addon)
    # ------------------------------------------------------------------ #

    history_summary = fields.Text(
        string='Conversation Summary',
        help=(
            'Rolling summary of this session generated by the LLM. '
            'Updated every 10 new messages using the same summarisation '
            'logic as the livechat module.'
        ),
    )

    last_summarized_count = fields.Integer(
        string='Last Summarised Count',
        default=0,
        readonly=True,
        help='Total number of messages that existed when the last summary was generated.',
    )

    # ------------------------------------------------------------------ #
    # Relations                                                            #
    # ------------------------------------------------------------------ #

    message_ids = fields.One2many(
        'mcp.chatbot.message',
        'session_id',
        string='Messages',
    )

    message_count = fields.Integer(
        string='Message Count',
        compute='_compute_message_count',
    )

    # ------------------------------------------------------------------ #
    # Computed fields                                                      #
    # ------------------------------------------------------------------ #

    @api.depends('partner_id', 'session_token', 'create_date')
    def _compute_name(self):
        for rec in self:
            if rec.partner_id:
                rec.name = f'{rec.partner_id.name} — {rec.create_date:%Y-%m-%d %H:%M}' if rec.create_date else rec.partner_id.name
            else:
                token_short = (rec.session_token or '')[:8]
                rec.name = f'Visitor #{token_short} — {rec.create_date:%Y-%m-%d %H:%M}' if rec.create_date else f'Visitor #{token_short}'

    @api.depends('message_ids')
    def _compute_message_count(self):
        for rec in self:
            rec.message_count = len(rec.message_ids)

    # ------------------------------------------------------------------ #
    # Business logic                                                        #
    # ------------------------------------------------------------------ #

    @api.model
    def get_or_create_session(self, session_token: str, partner_id: int = None) -> 'ChatbotSession':
        """
        Retrieve an existing open session by token or create a new one.

        Args:
            session_token: UUID generated by the browser widget.
            partner_id:    Odoo partner ID if the visitor is logged in.

        Returns:
            A mcp.chatbot.session record.
        """
        session = self.search([
            ('session_token', '=', session_token),
            ('state', '=', 'open'),
        ], limit=1)

        if not session:
            vals = {'session_token': session_token}
            if partner_id:
                vals['partner_id'] = partner_id
            session = self.create(vals)

        return session
    
    @api.model
    def get_latest_session_for_partner(self, partner_id: int):
        """Find the most recent open session for a logged-in partner."""
        return self.search([
            ('partner_id', '=', partner_id),
            ('state', '=', 'open'),
        ], order='create_date desc', limit=1)


    def action_close(self):
        """Close the session."""
        self.ensure_one()
        print("="*60)
        print(f"Session ({self.name}) is closed")
        print("="*60)
        self.write({'state': 'closed'})

    def touch_activity(self):
        """Update last_activity to now. Called on every incoming message to reset the idle clock."""
        self.write({'last_activity': fields.Datetime.now()})

    def get_conversation_history(self) -> list:
        """
        Return a list of {"role": ..., "content": ...} dicts for all messages
        in this session, sorted chronologically. Used to feed history into the
        MCP / LLM pipeline.
        """
        self.ensure_one()
        history = []
        for msg in self.message_ids.sorted('create_date'):
            history.append({
                'role': msg.role,
                'content': msg.content,
            })
        return history

    # ------------------------------------------------------------------ #
    # Cron: close idle sessions                                            #
    # ------------------------------------------------------------------ #

    @api.model
    def cron_close_idle_sessions(self):
        """
        Called by the scheduled action every 10 minutes.
        Closes any open session whose last_activity is older than
        IDLE_TIMEOUT_MINUTES (default 30).
        """
        self.ensure_one()
        IDLE_TIMEOUT_MINUTES = 30
        cutoff = fields.Datetime.now() - timedelta(minutes=IDLE_TIMEOUT_MINUTES)
        idle_sessions = self.search([
            ('state', '=', 'open'),
            ('last_activity', '<', cutoff),
        ])
        if idle_sessions:
            idle_sessions.action_close()
