import logging
from datetime import timedelta

from odoo import models, fields, api

_logger = logging.getLogger(__name__)


class ChatbotSession(models.Model):
    """
    Represents a single chat session between a website visitor and the AI chatbot.

    A session is created the first time a visitor sends a message from the website
    snippet. It stores the visitor's identity (if logged in, the partner is linked;
    otherwise only the browser-generated token is kept), the current LLM-ready
    conversation summary, and a count that mirrors the summarisation logic already
    used in the odoo_mcp_addon history system.
    """

    _name = 'mcp.chatbot.session'
    _description = 'MCP Chatbot Session'
    _order = 'create_date desc'

    # ------------------------------------------------------------------ #
    # Identity                                                             #
    # ------------------------------------------------------------------ #

    name = fields.Char(
        string='Session Name',
        compute='_compute_name',
        store=True,
    )

    # Opaque token generated by the browser widget (UUID‑v4).
    # Used to resume a session across page reloads without requiring login.
    # For logged‑in users this field is left empty.
    session_token = fields.Char(
        string='Session Token',
        index=True,
        copy=False,
    )

    # Populated only when the visitor is a logged-in Odoo portal / internal user.
    partner_id = fields.Many2one(
        'res.partner',
        string='Visitor (Partner)',
        ondelete='set null',
        index=True,
    )

    # ------------------------------------------------------------------ #
    # State                                                                #
    # ------------------------------------------------------------------ #

    state = fields.Selection(
        selection=[
            ('open',   'Open'),
            ('closed', 'Closed'),
        ],
        string='State',
        default='open',
        required=True,
        index=True,
    )

    # Tracks the last time a message was sent in this session.
    # Used by the cron job to close idle sessions after IDLE_TIMEOUT_MINUTES.
    last_activity = fields.Datetime(
        string='Last Activity',
        default=fields.Datetime.now,
        readonly=True,
    )

    # Set by the sidecar agent when an anonymous visitor starts email
    # verification (the `send_verification_email` tool fires). It signals
    # "this session is mid-checkout", so the per-user token budget grants a
    # small grace — letting an over-budget visitor finish the OTP + order flow
    # instead of being cut off and losing the sale. Reset to False naturally
    # on a fresh session; once the session is verified the grace is superseded
    # by the larger verified bonus.
    otp_pending = fields.Boolean(
        string='Verification In Progress',
        default=False,
        copy=False,
    )

    # ------------------------------------------------------------------ #
    # History compression (mirrors history.summary logic in odoo_mcp_addon)
    # ------------------------------------------------------------------ #

    history_summary = fields.Text(
        string='Conversation Summary',
        help=(
            'Rolling summary of this session generated by the LLM. '
            'Updated every 10 new messages using the same summarisation '
            'logic as the livechat module.'
        ),
    )

    last_summarized_count = fields.Integer(
        string='Last Summarised Count',
        default=0,
        readonly=True,
        help='Total number of messages that existed when the last summary was generated.',
    )

    # ------------------------------------------------------------------ #
    # Relations                                                            #
    # ------------------------------------------------------------------ #

    message_ids = fields.One2many(
        'mcp.chatbot.message',
        'session_id',
        string='Messages',
    )

    message_count = fields.Integer(
        string='Message Count',
        compute='_compute_message_count',
    )

    rating_ids = fields.One2many(
        'mcp.chatbot.rating',
        'session_id'
    )

    session_rating_text = fields.Selection([
        ('none', 'No Rating'),
        ('bad', 'Bad'),
        ('neutral', 'Neutral'),
        ('good', 'Good'),
    ], default='none', string="Rating", compute="_compute_session_rating_text", store=True)

    # ------------------------------------------------------------------ #
    # Computed fields                                                      #
    # ------------------------------------------------------------------ #

    @api.depends('partner_id', 'session_token', 'create_date')
    def _compute_name(self):
        for rec in self:
            if rec.partner_id:
                rec.name = f'{rec.partner_id.name} — {rec.create_date:%Y-%m-%d %H:%M}' if rec.create_date else rec.partner_id.name
            elif rec.session_token:
                token_short = (rec.session_token or '')[:8]
                rec.name = f'Visitor #{token_short} — {rec.create_date:%Y-%m-%d %H:%M}' if rec.create_date else f'Visitor #{token_short}'
            else:
                rec.name = f'Unidentified session — {rec.create_date:%Y-%m-%d %H:%M}' if rec.create_date else 'Unidentified session'

    @api.depends('message_ids')
    def _compute_message_count(self):
        for rec in self:
            rec.message_count = len(rec.message_ids)
    
    @api.depends('rating_ids.rating_text')
    def _compute_session_rating_text(self):
        for rec in self:
            rec.session_rating_text = 'none'
            if rec.rating_ids:
                rec.session_rating_text = rec.rating_ids[0].rating_text  

    # ------------------------------------------------------------------ #
    # Business logic                                                        #
    # ------------------------------------------------------------------ #

    @api.model
    def get_or_create_session(self, session_token: str = None, partner_id: int = None) -> 'ChatbotSession':
        """
        Retrieve an existing open session or create a new one.

        Args:
            session_token: UUID generated by the browser widget (for anonymous users).
            partner_id:    Odoo partner ID if the visitor is logged in.

        Returns:
            A mcp.chatbot.session record.

        Notes:
            - If partner_id is given, it takes precedence over session_token.
            - For logged‑in users, the session_token field remains empty.
        """
        if partner_id:
            session = self.search([
                ('partner_id', '=', partner_id),
                ('state', '=', 'open'),
            ], limit=1)
            if not session:
                session = self.create({'partner_id': partner_id, 'state': 'open'})
            return session

        if session_token:
            session = self.search([
                ('session_token', '=', session_token),
                ('state', '=', 'open'),
            ], limit=1)
            if not session:
                session = self.create({'session_token': session_token, 'state': 'open'})
            return session

        # Should never be called without at least one identifier
        raise ValueError('Either session_token or partner_id must be provided')

    def action_close(self):
        """Close the session."""
        for rec in self:
            print("="*60)
            print(f"Session ({rec.name}) is closed")
            print("="*60)
            rec.write({'state': 'closed'})

    def touch_activity(self):
        """Update last_activity to now. Called on every incoming message to reset the idle clock."""
        self.write({'last_activity': fields.Datetime.now()})

    def get_conversation_history(self) -> list:
        """
        Return a list of {"role": ..., "content": ...} dicts for all messages
        in this session, sorted chronologically. Used to feed history into the
        MCP / LLM pipeline.
        """
        self.ensure_one()
        history = []
        for msg in self.message_ids.sorted('create_date'):
            history.append({
                'role': msg.role,
                'content': msg.content,
            })
        return history

    # ------------------------------------------------------------------ #
    # Cron: close idle sessions                                            #
    # ------------------------------------------------------------------ #

    @api.model
    def cron_close_idle_sessions(self):
        """
        Called by the scheduled action every 10 minutes.
        Closes any open session whose last_activity is older than
        IDLE_TIMEOUT_MINUTES (default 30).
        """
        idle_timeout = int(
            self.env['ir.config_parameter'].sudo().get_param('mcp_chatbot.idle_timeout', 30)
        )
        cutoff = fields.Datetime.now() - timedelta(minutes=idle_timeout)
        idle_sessions = self.search([
            ('state', '=', 'open'),
            ('last_activity', '<', cutoff),
        ])
        if idle_sessions:
            idle_sessions.action_close()

    # ------------------------------------------------------------------ #
    # Cron: transcript retention                                           #
    # ------------------------------------------------------------------ #

    @api.model
    def cron_delete_old_conversations(self):
        """
        Called by the scheduled action once a day.
        Deletes closed conversations whose last activity is older than
        mcp_chatbot.transcript_retention_days (default 90; 0 disables).

        Transcripts contain PII (names, emails, order details), so they get
        a shelf life: keeping them ~90 days covers debugging, disputes and
        abuse investigation, while bounding both the privacy exposure and
        the damage a database leak could do. Messages and the rating are
        removed with the session (ondelete='cascade'); durable user
        knowledge lives in mcp.chatbot.user.fact and is NOT touched here.

        Only closed sessions are considered — open ones are closed by the
        idle cron within the hour, so anything months old is long closed.
        """
        retention_days = int(
            self.env['ir.config_parameter'].sudo().get_param(
                'mcp_chatbot.transcript_retention_days', 90
            )
        )
        if retention_days <= 0:
            return
        cutoff = fields.Datetime.now() - timedelta(days=retention_days)
        old_sessions = self.search([
            ('state', '=', 'closed'),
            ('last_activity', '<', cutoff),
        ])
        if old_sessions:
            count = len(old_sessions)
            old_sessions.unlink()
            _logger.info(
                "retention: deleted %d conversation(s) older than %d days",
                count, retention_days,
            )